### ISSUE TITLE
Simplify `IconButton`

### ISSUE THREAD

**Issue by beroset** [AsteroidOS/qml-asteroid#26]
The current version of `IconButton` can't be used in a QML `Row` or `Column` because it always tries to set anchors.  Better would be to eliminate `undefinedEdge`, `edge` and all of the `anchor` code which will simultaneously make the code more flexible and easier to understand.

**Comment by beroset** [comment]
I had forgotten to address the default case which had previously set the `edge` to `Qt.Bottom`.  These last few commits address that oversight.

**Comment by beroset** [comment]
Removed the now-redundant `enabled: visible` from asterioid-stopwatch and asteroid-timer.

**Comment by FlorentRevest** [comment]
Thank you beroset! These refactoring to improve our codebase health are awesome 😃
