### ISSUE TITLE
Create a Label component

### ISSUE THREAD

**Issue by FlorentRevest** [AsteroidOS/qml-asteroid#6]
Currently, QML apps use the QML Text element with the color *always* set to white.
In an effort to factorize code between apps qml-asteroid should provide a Label component inheriting Text and setting this property to white. Every app should be updated to use this component.
This component should also normalize the font.pixelSize used across every apps using Dims.l .

**Comment by rucuriousyet** [comment]
I might be interested in taking this on... can you give me some pointers as to where to find the files involved? I can easily componentize something but I have no knowledge of this project (was brought here by Hacktoberfest)

**Comment by FlorentRevest** [comment]
Hi Seth!

I'm glad Hacktoberfest brought you here. The idea of this task is to provide a new QML Item in qml-asteroid. You can find several examples of Items here: https://github.com/AsteroidOS/qml-asteroid/tree/master/src/controls/qml

You should start by creating a Label.qml file in this directory providing an Item inheriting QtQuick's Text. Integrate your Label well to the qml-asteroid build system and then start factorizing commonly used Text properties in Asteroid apps (the typical example being color: and font.pixelSize:, if you find something else that may be interesting to factorize, feel free to propose).

In order to validate the task, I would also want to see this new "Label" Item being used in most Asteroid apps. You can clone most "asteroid-*" repositories and grep for "Text" in every .qml files. Replace the usages of Text with your Label and simplify the code by removing the usage of the now redundant "color:", "font.pixelSize:" and maybe others properties... Those patches should touch plenty of repositories but be very simple (just one replaced line and a few removed lines).

This is a overall a very simple task but this requires to touch just a little bit of everything and this would need some time to setup a build environment.

Let us know if you have any other question
